import org.junit.jupiter.api.Assertions.*
import kotlin.io.path.Path
import kotlin.io.path.readText
import kotlin.test.Test

class Day07Test {

    @Test
    fun example1() {
        val exampleInput = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """.trimIndent().lines()
        val day = Day07()
        val result1 = day.part1(exampleInput)
        assertEquals(21, result1)
    }

    @Test
    fun example2() {
        val exampleInput = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """.trimIndent().lines()
        val day = Day07()
        val result1 = day.part2(exampleInput)
        assertEquals(40, result1)
    }


    @Test
    fun runPart1() {
        val input = Path("src/input.txt").readText().trim().lines()
        val part1 = Day07().part1(input)
        val part2 = Day07().part2(input)
        println("Result $part1")
        println("Result $part2")

    }

}